branch: true
ignore-not-existing: true
llvm: true
filter: covered
output-type: lcov
output-path: ./lcov.info
prefix-dir: /home/user/build/
ignore:
  - "../*"
  - "/*"
#path-mapping:
#- "/path1"
#- "/path2"
